services:
  postgres-shop-product: # service name must match the hostname in .env file.
    image: postgres:17.3
    container_name: postgres-shop-product
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_HOST_PORT}:${DATABASE_DOCKER_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - 'cart-demo'
  app:
    container_name: go-app-shop-product
    build:
      context: ../../
      dockerfile: deployments/dev/Dockerfile
    # ports:
    #   - 8083:1323
    expose:
      - 1323
    # Important to bind/mount codebase dir to /app dir for live reload
    volumes:
      - ../../:/app
    depends_on:
      postgres-shop-product:
        condition: service_healthy
    # labels are key-value metadata
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.shop-product-container.rule=PathPrefix(`/shop-product`)'
      # tells Traefik which port inside the container the service is listening on.
      - 'traefik.http.services.shop-product-container.loadbalancer.server.port=1323'
    networks:
      - 'cart-demo'

volumes:
  postgres-data:

networks:
  cart-demo:
    external: true
